# Generated by Django 4.2.14 on 2024-07-28 17:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("goal", models.CharField(max_length=100)),
                ("reflection", models.CharField(max_length=100)),
                ("self_evaluation", models.IntegerField(default=None)),
                ("score", models.IntegerField(default=None)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("S", "Shuffle"),
                            ("RC", "Reading Comprehension"),
                            ("LR", "Logical Reasoning"),
                        ],
                        default="LR",
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
